site_name: AndrewBreyen.github.io
site_url: https://andrewbreyen.github.io/
nav:
    - Home: index.md
    - Resume:
      - 'Education': 'resume/education.md'
      - 'Experience': 'resume/experience.md'
      - 'Extra Curricular and Service Activities': 'resume/extra-service.md'
    - Projects:
      - 'MacServer Documentation': 'projects/macserver-documentation.md'
    - Documentation:
      - 'Import Photos from iPhone': 'documentation/photos-import.md'
      - 'Google Photos': 'documentation/google-photos.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
plugins:
  - glightbox
